version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20

    commands:
      - echo "Installing frontend dependencies..."
      - cd frontend
      - npm ci

      - cd ../backend
      - echo "Installing backend dependencies..."
      - npm ci

      - cd ..

  pre_build:
    commands:
      - node -v
      - npm -v

  build:
    commands:
      - echo "Building React application..."
      - cd frontend
      - VITE_API_URL=$VITE_API_URL npm run build
      - cd ..

  post_build:
    commands:
      - echo "Build completed successfully."

artifacts:
  files:
    - '**/*'

cache:
  paths:
    - '/root/.npm/**/*'